[package]
name = "chemical_elements"
version = "0.1.0"
edition = "2018"

license = "Apache-2.0"
repository = "https://github.com/mobiusklein/chemical_composition"

description = "A library for representing chemical compositions and generating isotopic patterns"
documentation = "https://docs.rs/chemical_composition"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "chemical_elements"
src = "src/main.rs"

[lib]
name = "chemical_elements"


[dependencies]
lazy_static = "1.4.0"

[build-dependencies]
serde_json = "1.0"
