[package]
name = "chemical_elements"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "chemical_elements"
src = "src/main.rs"

[lib]
name = "chemical_elements"


[dependencies]
lazy_static = "1.4.0"

[build-dependencies]
serde_json = "1.0"
